# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: kolekulyanov/sail-runner:2.1
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '81:80'
        environment:
            WWWUSER: '${WWWUSER}'
            #LARAVEL_SAIL: 1
#        volumes:
#            - '.:/var/www/html'
